name: Build Flet APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v4

      - id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - id: setup-flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          # លោកអ្នកអាចបន្ថែម distribution: 'zulu' ខាងក្រោមនេះបានបើត្រូវការ
