name: Build Flet APK
on:
​​ push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - id: setup-flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Linux Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build libgtk-3-dev liblzma-dev libstdc++6

      - name: Install Flet and Build APK
        run: |
          pip install flet
          flet build apk --no-docker          

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flet-app-apk
          path: build/apk/*.apk
